addons:
  postgresql: '9.3'
services:
- postgresql
language: ruby
cache: bundler
rvm:
- 2.3.1
before_script:
- psql -c 'create database subkitchen_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: please-set
  app: subkitchen-api
  on:
    repo: jerrobison/subkitchen-api
  run: "rake db:migrate"
services:
  - redis-server
