default: &default
  adapter: postgresql
  username: postgres
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: subkitchen_api_development

test:
  <<: *default
  database: subkitchen_api_test

production:
   <<: *default
   database: subkitchen_api_production